//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingMaster
    {
        public int BookingID { get; set; }
        public System.DateTime BookingDate { get; set; }
        public string BookingReference { get; set; }
        public int HotelID { get; set; }
        public int RoomTypeID { get; set; }
        public string Title { get; set; }
        public bool IsAllDay { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public string StartTimezone { get; set; }
        public string EndTimezone { get; set; }
        public string CustomerName { get; set; }
        public string CustomerIdentityNo { get; set; }
        public Nullable<bool> CustomerSex { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerTelephone { get; set; }
        public string CustomerNationality { get; set; }
        public int ChargeTypeID { get; set; }
        public double AdvancePayment { get; set; }
        public bool IsPaidByATMCard { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public string RecurrenceRule { get; set; }
        public Nullable<int> RecurrenceID { get; set; }
        public string RecurrenceException { get; set; }
        public bool InActive { get; set; }
    
        public virtual ListRoomType ListRoomType { get; set; }
    }
}
