//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    
    public partial class HotelRoom
    {
        public int HotelID { get; set; }
        public int RoomID { get; set; }
        public string RoomDescription { get; set; }
        public string FloorLevel { get; set; }
        public string RoomRemarks { get; set; }
        public int RoomTypeID { get; set; }
        public string RoomTypeDescription { get; set; }
        public int NoBed { get; set; }
        public int BillingID { get; set; }
        public string RoomIcon { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public string CustomerName { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public string PromptDescription { get; set; }
        public int RoomCategoryID { get; set; }
        public string RoomCategoryDescription { get; set; }
        public string SpanWidth { get; set; }
        public string SpanHeight { get; set; }
        public string MarginLeft { get; set; }
        public string MarginRight { get; set; }
        public string IconWidth { get; set; }
    }
}
