//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListRoom
    {
        public ListRoom()
        {
            this.BillingMasters = new HashSet<BillingMaster>();
        }
    
        public int RoomID { get; set; }
        public string Description { get; set; }
        public int HotelID { get; set; }
        public int RoomTypeID { get; set; }
        public int RoomStatusID { get; set; }
        public string FloorLevel { get; set; }
        public int NoBed { get; set; }
        public int NoPerson { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<BillingMaster> BillingMasters { get; set; }
        public virtual ListHotel ListHotel { get; set; }
        public virtual ListRoomStatuses ListRoomStatu { get; set; }
        public virtual ListRoomType ListRoomType { get; set; }
    }
}
