//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListContextMenu
    {
        public int ContextMenuID { get; set; }
        public int ModuleID { get; set; }
        public string MenuCategory { get; set; }
        public string MenuValue { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public string MenuIcon { get; set; }
        public int MenuOrderNo { get; set; }
    }
}
