//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListChargeRate
    {
        public int ChargeRateID { get; set; }
        public int RoomTypeID { get; set; }
        public int ChargeTypeID { get; set; }
        public int ChargeVolumn { get; set; }
        public double ChargeRate { get; set; }
        public double ChargeRateUpper { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public int ChargeVolumnFirst { get; set; }
    
        public virtual ListChargeType ListChargeType { get; set; }
        public virtual ListRoomType ListRoomType { get; set; }
    }
}
