//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListChargeType
    {
        public ListChargeType()
        {
            this.BillingMasters = new HashSet<BillingMaster>();
            this.ListChargeRates = new HashSet<ListChargeRate>();
        }
    
        public int ChargeTypeID { get; set; }
        public string Description { get; set; }
        public double HoursPerBlock { get; set; }
        public double GraceMinutes { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<BillingMaster> BillingMasters { get; set; }
        public virtual ICollection<ListChargeRate> ListChargeRates { get; set; }
    }
}
