//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListRoomCategory
    {
        public ListRoomCategory()
        {
            this.ListRoomTypes = new HashSet<ListRoomType>();
        }
    
        public int RoomCategoryID { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public string SpanWidth { get; set; }
        public string SpanHeight { get; set; }
        public string MarginLeft { get; set; }
        public string MarginRight { get; set; }
        public string IconWidth { get; set; }
    
        public virtual ICollection<ListRoomType> ListRoomTypes { get; set; }
    }
}
