//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingMaster
    {
        public BillingMaster()
        {
            this.BillingDetails = new HashSet<BillingDetail>();
        }
    
        public int BillingID { get; set; }
        public System.DateTime BillingDate { get; set; }
        public string BillingReference { get; set; }
        public int RoomID { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerIdentityNo { get; set; }
        public Nullable<bool> CustomerSex { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerTelephone { get; set; }
        public string CustomerNationality { get; set; }
        public int ChargeTypeID { get; set; }
        public double ChargeDuration { get; set; }
        public double ChargeAmount { get; set; }
        public double ServiceAmount { get; set; }
        public double OtherAmount { get; set; }
        public double DiscountPercent { get; set; }
        public double DiscountAmount { get; set; }
        public double TotalAmount { get; set; }
        public double AdvancePayment { get; set; }
        public bool IsPaidByATMCard { get; set; }
        public bool IsCheckOut { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> BookingID { get; set; }
    
        public virtual ICollection<BillingDetail> BillingDetails { get; set; }
        public virtual ListChargeType ListChargeType { get; set; }
        public virtual ListRoom ListRoom { get; set; }
    }
}
