//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    
    public partial class HotelFloorLevel
    {
        public int HotelID { get; set; }
        public string Description { get; set; }
        public string FloorLevel { get; set; }
    }
}
