//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListHotel
    {
        public ListHotel()
        {
            this.ListRooms = new HashSet<ListRoom>();
        }
    
        public int HotelID { get; set; }
        public string Description { get; set; }
        public int LocationID { get; set; }
        public string Remarks { get; set; }
        public int HotelOrderNo { get; set; }
        public string Name { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
    
        public virtual ListLocation ListLocation { get; set; }
        public virtual ICollection<ListRoom> ListRooms { get; set; }
    }
}
