//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListRoomType
    {
        public ListRoomType()
        {
            this.ListChargeRates = new HashSet<ListChargeRate>();
            this.ListRooms = new HashSet<ListRoom>();
            this.BookingMasters = new HashSet<BookingMaster>();
        }
    
        public int RoomTypeID { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public string IconIdle { get; set; }
        public string IconBusy { get; set; }
        public int RoomCategoryID { get; set; }
    
        public virtual ICollection<ListChargeRate> ListChargeRates { get; set; }
        public virtual ICollection<ListRoom> ListRooms { get; set; }
        public virtual ListRoomCategory ListRoomCategory { get; set; }
        public virtual ICollection<BookingMaster> BookingMasters { get; set; }
    }
}
