//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListService
    {
        public ListService()
        {
            this.BillingDetails = new HashSet<BillingDetail>();
            this.PurchaseInvoiceDetails = new HashSet<PurchaseInvoiceDetail>();
        }
    
        public int ServiceID { get; set; }
        public string Description { get; set; }
        public string UnitForSales { get; set; }
        public double UnitPrice { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<BillingDetail> BillingDetails { get; set; }
        public virtual ICollection<PurchaseInvoiceDetail> PurchaseInvoiceDetails { get; set; }
    }
}
