//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoice
    {
        public PurchaseInvoice()
        {
            this.PurchaseInvoiceDetails = new HashSet<PurchaseInvoiceDetail>();
        }
    
        public int PurchaseInvoiceID { get; set; }
        public System.DateTime PurchaseInvoiceDate { get; set; }
        public string PurchaseInvoiceReference { get; set; }
        public string SupplierName { get; set; }
        public string AttentionName { get; set; }
        public decimal TotalQuantity { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal TotalVATAmount { get; set; }
        public decimal TotalGrossAmount { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime EditedDate { get; set; }
        public int UserID { get; set; }
        public int UserPositionID { get; set; }
        public int HotelID { get; set; }
    
        public virtual ICollection<PurchaseInvoiceDetail> PurchaseInvoiceDetails { get; set; }
    }
}
